### ISSUE TITLE
Get rid of more slave references

### ISSUE THREAD

**Issue by RichiH** [mxinden/modbus_exporter#16]
Like https://github.com/RichiH/modbus_exporter/issues/1 , but through the whole codebase. `target` should be suitable in most cases.

**Comment by mxinden** [comment]
```bash
$ grep -ri -E "slave" | grep -v vendor
modbus/modbus.go:       handler.SlaveId = subTarget
```

Only reference of the word is a call into the modbus library. Hence I am closing here.

**Comment by RichiH** [comment]
Thanks!

Sent by mobile; please excuse my brevity.
